"""Added a default time of now to the timestamp attribute of the OTP table

Revision ID: 06125bef337f
Revises: 9a545153431b
Create Date: 2024-03-01 20:30:12.992924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06125bef337f'
down_revision = '9a545153431b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
