"""Added a file data attribute in the leave applications model

Revision ID: 669c476a0858
Revises: cbf3d7c2f899
Create Date: 2024-02-15 18:32:24.504305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669c476a0858'
down_revision = 'cbf3d7c2f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
