"""MaAdded normal leave to the leave type enum values

Revision ID: 79921431a7e0
Revises: 57bfb1a1a22f
Create Date: 2024-02-16 16:22:01.372327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79921431a7e0'
down_revision = '57bfb1a1a22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.alter_column('leave_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('Sick', 'Maternity', 'Paternity', 'Normal'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.alter_column('leave_type',
               existing_type=sa.Enum('Sick', 'Maternity', 'Paternity', 'Normal'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
