"""Added a firstLogin boolean attribute

Revision ID: a6d77d6dc09a
Revises: cb784fe6744c
Create Date: 2024-02-29 10:45:08.073140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d77d6dc09a'
down_revision = 'cb784fe6744c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstLogin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('firstLogin')

    # ### end Alembic commands ###
